### ISSUE TITLE
openai.error.InvalidRequestError: This model's maximum context length is 8191 tokens, however you requested 14626 tokens (14626 in your prompt; 0 for the completion). 

### ISSUE THREAD

**Issue by Leedefend** [kaqijiang/Auto-GPT-ZH#1]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Your prompt 📝

```yaml
使用中文版的Auto-GPT始终会出现这个问题，调用openAI时tokens长度超限，求解决！
```

**Comment by AlexANSO** [comment]
这个是本身的限制，是咱的数据太大了，超过了限制8191tokens

**Comment by kaqijiang** [comment]
或者你可以描述任务的时候少一些。
