### ISSUE TITLE
autogpt分支问题

### ISSUE THREAD

**Issue by beebon** [kaqijiang/Auto-GPT-ZH#12]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

autogpt官网不是建议用stable分支吗，是不是可以改用该分支而不是主分支呢

### Examples 🌈

https://github.com/Significant-Gravitas/Auto-GPT/tree/stable

### Motivation 🔦

https://github.com/Significant-Gravitas/Auto-GPT/tree/stable

**Comment by kaqijiang** [comment]
master 对应的就是原项目的stable
