### ISSUE TITLE
.env.template中携带了私人api-key，注意安全~

### ISSUE THREAD

**Issue by ArvinLake** [kaqijiang/Auto-GPT-ZH#2]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by kaqijiang** [comment]
谢谢，我知道 这个没费用了
