### ISSUE TITLE
抛出以下错误: 'dict' object has no attribute 'replace'

### ISSUE THREAD

**Issue by wdc8866** [kaqijiang/Auto-GPT-ZH#5]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/18025501/233027443-60c2e4ed-30c1-4b02-90d9-aa557a961c1e.png">
经常出现这个错误

**Comment by hd19820806** [comment]
同理， 感觉这个版本。配置文件注销的太多了，几乎不能用

**Comment by kaqijiang** [comment]
这个是请求网站返回的数据，可能是网络问题，可能是对方网站报错。存在情况很多，暂时无需处理
